export const TYPES = {
  SET_SONGS: 'SET_SONGS',
  SET_SONG_SELECTED: 'SET_SONG_SELECTED',
  SET_ID_ARTIST: 'SET_ID_ARTIST',
  SAVE_SONG_RECENT: 'SAVE_SONG_RECENT',
  SET_VALUE_SEARCH: 'SET_VALUE_SEARCH'
}